###################################
#
# Copyright (c) 2022 KangarooKube
#
###################################

SHELL                := /bin/bash
BUILD_ROOT           = $(shell git rev-parse --show-toplevel)/release/build

create-new-release:
	@cd $(BUILD_ROOT) && ./create-new-release.sh
