apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-arc-kubernetes-bootstrap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # TODO: RBAC-granularize once HAIKU least-privelege helm charts are released
subjects:
  - kind: ServiceAccount
    name: azure-arc-kubernetes-bootstrap
    namespace: azure-arc-kubernetes-bootstrap