apiVersion: batch/v1
kind: Job
metadata:
  name: azure-arc-kubernetes-bootstrap
  namespace: azure-arc-kubernetes-bootstrap
spec:
  template:
    spec:
      serviceAccountName: azure-arc-kubernetes-bootstrap
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux
      volumes:
      - name: dc-config
        configMap:
          name: dc-config
      containers:
      - name: azure-arc-kubernetes-bootstrap
        imagePullPolicy: Always
        image: kube-arc-data-services-installer-job
        volumeMounts:
        - name: dc-config
          mountPath: /home/container-user/custom
        env:
        - name: VERBOSE
          value: "false"
        - name: CUSTOM_LOCATION_OID
          value: 51dfe1e8-70c6-4de5-a08e-e18aff23d815
        - name: ONBOARDING_TIMEOUT
          value: "900"
        - name: OPENSHIFT
          value: "false"
        - name: DELETE_FLAG
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: DELETE_FLAG
              optional: true
        - name: TENANT_ID
          valueFrom: 
            secretKeyRef:
              name: secret-envs
              key: TENANT_ID
        - name: SUBSCRIPTION_ID
          valueFrom: 
            secretKeyRef:
              name: secret-envs
              key: SUBSCRIPTION_ID
        - name: CLIENT_ID
          valueFrom: 
            secretKeyRef:
              name: secret-envs
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom: 
            secretKeyRef:
              name: secret-envs
              key: CLIENT_SECRET
        - name: AZDATA_USERNAME
          valueFrom: 
            secretKeyRef:
              name: secret-envs
              key: AZDATA_USERNAME
        - name: AZDATA_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret-envs
              key: AZDATA_PASSWORD
        - name: CONNECTED_CLUSTER_RESOURCE_GROUP
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: CONNECTED_CLUSTER_RESOURCE_GROUP
        - name: CONNECTED_CLUSTER
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: CONNECTED_CLUSTER
        - name: CONNECTED_CLUSTER_LOCATION
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: CONNECTED_CLUSTER_LOCATION
        - name: ARC_DATA_RESOURCE_GROUP
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: ARC_DATA_RESOURCE_GROUP
        - name: ARC_DATA_LOCATION
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: ARC_DATA_LOCATION
              optional: true
        - name: ARC_DATA_EXT
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: ARC_DATA_EXT
        - name: ARC_DATA_EXT_AUTO_UPGRADE
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: ARC_DATA_EXT_AUTO_UPGRADE
              optional: true
        - name: ARC_DATA_EXT_VERSION
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: ARC_DATA_EXT_VERSION
              optional: true
        - name: ARC_DATA_NAMESPACE
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: ARC_DATA_NAMESPACE
        - name: ARC_DATA_CONTROLLER
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: ARC_DATA_CONTROLLER
        - name: ARC_DATA_CONTROLLER_LOCATION
          valueFrom: 
            configMapKeyRef:
              name: config-envs
              key: ARC_DATA_CONTROLLER_LOCATION
      restartPolicy: Never
  backoffLimit: 4