resources:
  - job.yaml
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - namespace.yaml
configMapGenerator:
- name: config-envs
  namespace: azure-arc-kubernetes-bootstrap
  envs:
  - configs/configMap.env
secretGenerator:
- name: secret-envs
  namespace: azure-arc-kubernetes-bootstrap
  envs:
  - configs/secret.env
images:
- name: kube-arc-data-services-installer-job
  newName: ${IMAGE_REGISTRY}/kube-arc-data-services-installer-job
  newTag: ${IMAGE_TAG}