name: Integration Tests

on:
  pull_request:
    branches:
      - 'main'

  push:
    # For initial testing purposes - remove to not break the bank in future!
    branches: [ '*' ]
    # Only trigger for changes in these paths
    paths:
    - "ci/**"
    - "kustomize/**"
    - "src/**"
    - ".github/workflows/integration-test.yaml"

# Limit concurrent runs
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

# Replace these to modify Job parameters
env:
  SPN_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
  SPN_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
  SPN_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
  SPN_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
  AZDATA_USERNAME : boor
  AZDATA_PASSWORD : acntorPRESTO!
  CONNECTED_CLUSTER_LOCATION : eastus
  ARC_DATA_LOCATION : eastus
  CONNECTED_CLUSTER : clusterName
  ARC_DATA_EXT : arc-data-bootstrapper
  ARC_DATA_NAMESPACE : azure-arc-data
  ARC_DATA_CONTROLLER : azure-arc-data-controller
  ARC_DATA_CONTROLLER_LOCATION : eastus

jobs:
  go-tests:
    name: Run Integration Tests on fresh Kubernetes Clusters(s)
    runs-on: ubuntu-latest

    # For publishing Test Results
    permissions:
      checks: write
      pull-requests: write

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.3
          terraform_wrapper: false

      - uses: docker-practice/actions-setup-docker@master
      - name: Validate Docker install
        run: docker version

      - uses: azure/setup-kubectl@v2.0
      - name: Validate Kubectl install
        run: kubectl version --client

      - name: Download Go modules
        working-directory: ci/test
        run: go mod download

      - name: Run Integration tests for all release trains in parallel - preview, stable - in parallel
        working-directory: ci/test
        run: make -j integration-test-aks

      - uses: actions/upload-artifact@v2
        with:
          name: integration-test-result-all
          path: ci/test/integration-test-*

  publish-badge-preview:
    name: Publish badge from run - Preview
    needs: go-tests
    uses: ./.github/workflows/publish-badge.yaml
    with:
      run_artifact: integration-test-result-all
      xml_file_path: integration-test-report-preview.xml
      badge_file_name: integration-test-report-preview-badge.svg
      check_name: Integration Test - Preview
    secrets:
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

  publish-badge-stable:
    name: Publish badge from run - Stable
    needs: go-tests
    uses: ./.github/workflows/publish-badge.yaml
    with:
      run_artifact: integration-test-result-all
      xml_file_path: integration-test-report-stable.xml
      badge_file_name: integration-test-report-stable-badge.svg
      check_name: Integration Test - Stable
    secrets:
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}