name: Integration Tests
'on':
  schedule:
    - cron: 45 0 * * *
  push:
    branches:
      - '*'                             # No infra required, so we can run these per push
  pull_request:
    branches:
      - main
jobs:
  go-tests:
    name: Run Integration Tests (terratest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.3
          terraform_wrapper: false
      - name: Download Go modules
        working-directory: ci/test
        run: go mod download
      - name: Run tests
        working-directory: ci/test
        run: make integration-test
        # We only include the SPN because our Job will not be deployed here
        env:
          SPN_CLIENT_ID: '${{ secrets.SPN_CLIENT_ID }}'
          SPN_CLIENT_SECRET: '${{ secrets.SPN_CLIENT_SECRET }}'
          SPN_SUBSCRIPTION_ID: '${{ secrets.SPN_SUBSCRIPTION_ID }}'
          SPN_TENANT_ID: '${{ secrets.SPN_TENANT_ID }}'