name: Integration Tests

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

env:
  PERSON_NAME: ${{ github.event.inputs.name }}

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ env.PERSON_NAME }}"