name: Integration Tests

on:
  pull_request:
    branches:
      - 'main'

  # For initial testing purposes - remove to not break the bank!
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: false

# Replace these to modify Job parameters
env:
  SPN_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
  SPN_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
  SPN_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
  SPN_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
  AZDATA_USERNAME : boor
  AZDATA_PASSWORD : acntorPRESTO!
  CONNECTED_CLUSTER_LOCATION : eastasia
  ARC_DATA_LOCATION : eastasia
  CONNECTED_CLUSTER : clusterName
  ARC_DATA_EXT : arc-data-bootstrapper
  ARC_DATA_EXT_AUTO_UPGRADE : false
  ARC_DATA_EXT_VERSION : 1.2.19831003
  ARC_DATA_NAMESPACE : azure-arc-data
  ARC_DATA_CONTROLLER : azure-arc-data-controller
  ARC_DATA_CONTROLLER_LOCATION : southeastasia

jobs:
  go-tests:
    name: Run Integration Tests (terratest) on Kubernetes Cluster(s)
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.3
          terraform_wrapper: false

      - uses: docker-practice/actions-setup-docker@master
      - name: Validate Docker install
        run: docker version

      - uses: azure/setup-kubectl@v2.0
      - name: Validate Kubectl install
        run: kubectl version --client

      - name: Download Go modules
        working-directory: ci/test
        run: go mod download

      - name: Run Integration tests
        working-directory: ci/test
        run: make integration-test
