name: Nightly Docker Image Publish

on:
  schedule:
    - cron: '45 0 * * *'
  push:
    branches: [ "test-nightly-build" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Pull build args for stable build
      - name: Build ARGs from stable release file
        run: |
          export BUILD_ARGS=$(grep -v '^#' release/release.stable.env | xargs | sed 's/ /,/g')
          echo BUILD_ARGS=$BUILD_ARGS >> $GITHUB_ENV

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build image for scanning local
      - name: Build local container
        uses: docker/build-push-action@v3
        with:
          tags: stable-scan
          build-args: ${{ env.BUILD_ARGS }}
          push: false
          load: true
      
      # Local scan image for vulnerabilities 
      - name: Scan image for Vulnerabilities
        id: scan-image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'stable-scan'
          exit-code: '1'
          ignore-unfixed: false
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'trivy-results.sarif'

      # Upload scan results
      - name: Upload scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
        
      # Build and push Docker image with Buildx (don't push on push)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'push' }} # 'pull_request'
          tags: stable,latest
          labels: ${{ steps.meta.outputs.labels }}
