name: Unit Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    # Unit tests are cheap, so we can run them on every branch
    branches: [ '*' ]
    # Only trigger for changes in these paths
    paths:
    - "ci/**"
    - "kustomize/**"
    - "src/**"
    - ".github/workflows/unit-test.yaml"

jobs:
  go-tests:
    name: Run Unit Tests (terratest)
    runs-on: ubuntu-latest

    # For publishing Test Results
    permissions:
      checks: write
      pull-requests: write

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.3
          terraform_wrapper: false

      - name: Download Go modules
        working-directory: ci/test
        run: go mod download

      - name: Run Unit tests
        working-directory: ci/test
        # We only include the SPN because our Job will not be deployed here
        env:
          SPN_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          SPN_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          SPN_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
          SPN_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
        run: make unit-test

      - uses: actions/upload-artifact@v2
        with:
          name: unit-test-result
          path: ci/test/unit-test-*

  publish-badge:
    name: Publish badge from run
    needs: go-tests
    uses: ./.github/workflows/publish-badge.yaml
    with:
      xml_file_artifact: unit-test-result
      xml_file_path: unit-test-report.xml
      badge_file_name: unit-test-badge.svg
      check_name: Unit Test Results
    secrets:
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}