name: Unit Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    # Unit tests are cheap, so we can run them on every branch
    branches: [ '*' ]
    # Only trigger for changes in these paths
    paths:
    - "ci/**"
    - "kustomize/**"
    - "src/**"
    - ".github/workflows/unit-test.yaml"

jobs:
  go-tests:
    name: Run Unit Tests (terratest)
    runs-on: ubuntu-latest

    # For publishing Test Results
    permissions:
      checks: write
      pull-requests: write

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.3
          terraform_wrapper: false

      - name: Download Go modules
        working-directory: ci/test
        run: go mod download

      - name: Run Unit tests
        working-directory: ci/test
        # We only include the SPN because our Job will not be deployed here
        env:
          SPN_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
          SPN_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
          SPN_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
          SPN_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
        run: make unit-test

      - name: Generate Test Summary
        uses: test-summary/action@v1
        with:
          paths: |
                        ci/test/unit-test-report.xml
        if: always()

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        id: test-results
        if: always()
        with:
          files: "ci/test/unit-test-report.xml"
          check_name: Unit Test Results
          comment_title: "Unit Test Results"
          comment_mode: always

      - name: Set badge color
        shell: bash
        run: |
          case ${{ fromJSON( steps.test-results.outputs.json ).conclusion }} in
            success)
              echo "BADGE_COLOR=31c653" >> $GITHUB_ENV
              ;;
            failure)
              echo "BADGE_COLOR=800000" >> $GITHUB_ENV
              ;;
            neutral)
              echo "BADGE_COLOR=696969" >> $GITHUB_ENV
              ;;
          esac

      - name: Create badge
        uses: emibcn/badge-action@d6f51ff11b5c3382b3b88689ae2d6db22d9737d1
        with:
          label: Unit Tests
          status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
          color: ${{ env.BADGE_COLOR }}
          path: unit-test-badge.svg

      - name: Upload badge to Gist
        # Upload only for master branch
        if: >
          github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.event.workflow_run.head_branch == 'master' || github.event.workflow_run.head_branch == 'main'
        uses: andymckay/append-gist-action@1fbfbbce708a39bd45846f0955ed5521f2099c6d
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.githubusercontent.com/mdrakiburrahman/3f7efaed392e80ea103bb77441e0aa4a
          file: unit-test-badge.svg